service: first-example

provider:
  name: aws
  runtime: nodejs4.3

functions:
  currentTime:
    handler: handler.currentTime
    events:
      - http:
         path: current-time
         method: get
