controllers:
  main:
    containers:
      main:
        image:
          # repository: set via values.yaml
          # tag: set via values.yaml
          # https://iximiuz.com/en/posts/kubernetes-kind-load-docker-image/
          pullPolicy: Never
        probes:
          startup:
            enabled: false
          liveness:
            enabled: false
          readiness:
            enabled: false
service:
  main:
    ports:
      http:
        port: &port 3000
