language: node_js
node_js:
  - '0.10'

cache:
  directories:
    - vendor/bundle
    - node_modules

before_install:
  - sudo pip install PyOpenSSL
  - openssl aes-256-cbc -K $encrypted_61236829dce9_key -iv $encrypted_61236829dce9_iv -in $PROJECT_ID.p12.enc -out $PROJECT_ID.p12 -d
  - curl https://sdk.cloud.google.com | bash
  - $HOME/google-cloud-sdk/bin/gcloud components update app -q
  - $HOME/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
  - $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account $SRV_ACCOUNT --key-file $PROJECT_ID.p12
  - npm install --global gulp && npm install
  
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
  - PROJECT_ID=qrsnapper
  - SRV_ACCOUNT=972466464352-3jqc7trki71pfa25atovoq6meh31fmve@developer.gserviceaccount.com
  
after_success:
 - $HOME/google-cloud-sdk/bin/gcloud preview app deploy --version $TRAVIS_BRANCH ./app.yaml

# branch whitelist
branches:
  only:
  - production
  - slow
  
# Work out the deployment to app engine.

script:
  - gulp
