name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable yarn

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

      - name: Run turbo
        run: SKIP_ENV_VALIDATION=true yarn turbo --env-mode=loose typecheck build

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run turbo
        run: SKIP_ENV_VALIDATION=true DOCKER_IMAGE_REPOSITORY=ghcr.io/ewnd9/instagram-saved yarn turbo --env-mode=loose build test containerize
